service: grub

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: nodejs6.10
  stage: beta

functions:
  hello:
    description: Says hello!
    handler: handler.hello
